---
title: "Untitled"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
library(patchwork)
library(scales)
library(lme4)
library(lmerTest)
library(ggplot2)
```

```{r}

d <- read.csv('../data/processed/data.csv')
d

```

```{r}

fit0 = lmer(lf_count_log ~ else_freq_log + (1|lang) + (1|field), data=d)
summary(fit0)

fit1 = lmer(lf_count_log ~ narr_freq_log + (1|lang) + (1|field), data=d)
summary(fit1)

anova(fit0, fit1)

```

```{r}

plt_count_nar = d %>%
    ggplot(aes(narr_freq*1e6, lf_count)) +
    geom_point(alpha=0.1) +
    geom_smooth(formula = y~x, method = 'lm') +
    xlab('Narrative Frequency') +
    ylab('Count') +
    theme_bw(base_size=22) +
    scale_x_continuous(trans='log1p',
                       labels = label_number(scale_cut = cut_si(''))) +
    scale_y_continuous(trans='log1p') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))
plt_count_nar

plt_count_els = d %>%
    ggplot(aes(else_freq*1e6, lf_count)) +
    geom_point(alpha=0.1) +
    geom_smooth(formula = y~x, method = 'lm') +
    xlab('Non-Narrative Frequency') +
    ylab('Count') +
    theme_bw(base_size=22) +
    scale_x_continuous(trans='log1p',
                       labels = label_number(scale_cut = cut_si(''))) +
    scale_y_continuous(trans='log1p') +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))
plt_count_els

plt_count_nar + plt_count_els

```

```{r}

r2_c_wo = cor.test(d$lf_count_log, predict(fit0))$estimate**2
r2_c_wo_text <- paste("R^2 ==", round(r2_c_wo, 2))

r2_c_w1 = cor.test(d$lf_count_log, predict(fit1))$estimate**2
r2_c_w1_text <- paste("R^2 ==", round(r2_c_w1, 2))

plt_cou_wo = d %>%
    mutate(pred = predict(fit0)) %>%
    ggplot(aes(lf_count_log, pred)) +
    geom_abline(slope=1) +
    geom_point(alpha=0.05) +
    annotate("text", x = Inf, y = -Inf, vjust=-0.5, hjust=1.1, 
             label = r2_c_wo_text, parse = TRUE, size = 9) +
    theme_bw(base_size=22) +
    ylab('Count Prediction') + xlab('Count Data') +
    ggtitle('Non-Narrative Model') +
    coord_equal()
plt_cou_wo

plt_cou_w1 = d %>%
    mutate(pred = predict(fit1)) %>%
    ggplot(aes(lf_count_log, pred)) +
    geom_abline(slope=1) +
    geom_point(alpha=0.05) +
    annotate("text", x = Inf, y = -Inf, vjust=-0.5, hjust=1.1, 
             label = r2_c_w1_text, parse = TRUE, size = 9) +
    theme_bw(base_size=22) +
    ylab('Count Prediction') + xlab('Count Data') +
    ggtitle('Narrative Model') +
    coord_equal()
plt_cou_w1

plt_cou_wo + plt_cou_w1

```

```{r}

fit0e = lmer(lf_entropy ~ else_freq_log + (1|lang) + (1|field), data=d)
summary(fit0e)

fit1e = lmer(lf_entropy ~ narr_freq_log + (1|lang) + (1|field), data=d)
summary(fit1e)

anova(fit0e, fit1e)

```

```{r}
plt_ent_nar = d %>%
    ggplot(aes(narr_freq*1e6, lf_entropy)) +
    geom_point(alpha=0.1) +
    geom_smooth(formula = y~x, method = 'lm') +
    xlab('Narrative Frequency') +
    ylab('Entropy') +
    theme_bw(base_size=22) +
    scale_x_continuous(trans='log1p',
                       labels = label_number(scale_cut = cut_si(''))) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))
plt_ent_nar

plt_ent_els = d %>%
    ggplot(aes(else_freq*1e6, lf_entropy)) +
    geom_point(alpha=0.1) +
    geom_smooth(formula = y~x, method = 'lm') +
    xlab('Non-Narrative Frequency') +
    ylab('Entropy') +
    theme_bw(base_size=22) +
    scale_x_continuous(trans='log1p',
                       labels = label_number(scale_cut = cut_si(''))) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))
plt_ent_els

```

```{r}

r2_e_wo = cor.test(d$lf_entropy, predict(fit0e))$estimate**2
r2_e_wo_text <- paste("R^2 ==", round(r2_e_wo, 2))

r2_e_w1 = cor.test(d$lf_entropy, predict(fit1e))$estimate**2
r2_e_w1_text <- paste("R^2 ==", round(r2_e_w1, 2))

plt_ent_wo = d %>%
    mutate(pred = predict(fit0)) %>%
    ggplot(aes(lf_entropy, pred)) +
    geom_abline(slope=1) +
    geom_point(alpha=0.05) +
    annotate("text", x = Inf, y = -Inf, vjust=-0.5, hjust=1.1, 
             label = r2_e_wo_text, parse = TRUE, size = 9) +
    theme_bw(base_size=22) +
    ylab('Entropy Prediction') + xlab('Entropy Data') +
    ggtitle('Non-Narrative Model') +
    coord_equal()
plt_ent_wo

plt_ent_w1 = d %>%
    mutate(pred = predict(fit1e)) %>%
    ggplot(aes(lf_entropy, pred)) +
    geom_abline(slope=1) +
    geom_point(alpha=0.05) +
    annotate("text", x = Inf, y = -Inf, vjust=-0.5, hjust=1.1, 
             label = r2_e_w1_text, parse = TRUE, size = 9) +
    theme_bw(base_size=22) +
    ylab('Entropy Prediction') + xlab('Entropy Data') +
    ggtitle('Narrative Model') +
    coord_equal()
plt_ent_w1

plt_ent_wo + plt_ent_w1

```

```{r}

plt_count_nar + plt_count_els + plt_ent_nar + plt_ent_els + plot_layout(nrow=1)

plt_cou_wo + plt_cou_w1 + plt_ent_wo + plt_ent_w1 + plot_layout(nrow=1)


plt_count_nar + plt_count_els + plt_ent_nar + plt_ent_els + plt_cou_wo + plt_cou_w1 + plt_ent_wo + plt_ent_w1 + plot_layout(nrow=2)

ggsave('../figures/results.svg', width=20, height=10.6)

```
